### ISSUE TITLE
[FEATURE] - [Skills] - get a speed value

### ISSUE THREAD

**Issue by raphlmiranda** [lucasmonstrox/tibiapi#22] opened 2024-01-26 01:07 UTC
Is your feature request related to a problem? Please describe.
-

Describe the solution you'd like
Create a method to return a speed value

Describe alternatives you've considered
-

Additional context
-

**Comment by lucasmonstrox** [comment] 2024-01-26 02:01
@raphlmiranda already did it yesterday. Duplicate of https://github.com/lucasmonstrox/tibiapi/issues/20.

**Closed by lucasmonstrox** 2024-01-26 02:01 UTC
Labels: enhancement
